settings:
  bucket: "bucket_name"
  template_paths:
    element_templates_folder: "/templates/h5p/elements" # refers to folder in storage
    unit_template_path: "/templates/h5p/units/unit.h5p"
defaults:
  unit_title: "Unit"
  
slide_types:
  text:
    template_key: "text" 

  single_choice:
    template_key: "single_choice"
    preprocess: "single_choice"

  drag_text:
    template_key: "drag_text"
